// Code generated by k8s code-generator DO NOT EDIT.



// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	internalinterfaces "github.com/kubeflow/spark-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ScheduledSparkApplications returns a ScheduledSparkApplicationInformer.
	ScheduledSparkApplications() ScheduledSparkApplicationInformer
	// SparkApplications returns a SparkApplicationInformer.
	SparkApplications() SparkApplicationInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ScheduledSparkApplications returns a ScheduledSparkApplicationInformer.
func (v *version) ScheduledSparkApplications() ScheduledSparkApplicationInformer {
	return &scheduledSparkApplicationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// SparkApplications returns a SparkApplicationInformer.
func (v *version) SparkApplications() SparkApplicationInformer {
	return &sparkApplicationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
