apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-operator-webhook
  namespace: system
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/component: webhook
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - spark-operator-webhook-certs
    verbs:
      - get
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    resourceNames:
      - spark-operator-webhook-lock
    verbs:
      - get
      - update
