apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: webhook
  namespace: system
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/component: webhook
