apiVersion: v1
kind: Service
metadata:
  name: spark-operator-webhook-svc
  namespace: system
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/component: webhook
spec:
  selector:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/component: webhook
  ports:
    - port: 443
      targetPort: webhook
      name: webhook
