kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  GenericWorkload: true
  GangScheduling: true
runtimeConfig:
  scheduling.k8s.io/v1alpha2: "true"
nodes:
  - role: control-plane
  - role: worker
    labels:
      workload-e2e-driver: "true"
  - role: worker
    labels:
      workload-e2e-executor: "true"
