# coding: utf-8

"""
    Kubeflow Spark Operator OpenAPI Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: unversioned
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SparkV1beta2PrometheusSpec(BaseModel):
    """
    PrometheusSpec defines the Prometheus specification when Prometheus is to be used for collecting and exposing metrics.
    """ # noqa: E501
    config_file: Optional[StrictStr] = Field(default=None, description="ConfigFile is the path to the custom Prometheus configuration file provided in the Spark image. ConfigFile takes precedence over Configuration, which is shown below.", alias="configFile")
    configuration: Optional[StrictStr] = Field(default=None, description="Configuration is the content of the Prometheus configuration needed by the Prometheus JMX exporter. If not specified, the content in spark-docker/conf/prometheus.yaml will be used. Configuration has no effect if ConfigFile is set.")
    jmx_exporter_jar: StrictStr = Field(description="JmxExporterJar is the path to the Prometheus JMX exporter jar in the container.", alias="jmxExporterJar")
    port: Optional[StrictInt] = Field(default=None, description="Port is the port of the HTTP server run by the Prometheus JMX exporter. If not specified, 8090 will be used as the default.")
    port_name: Optional[StrictStr] = Field(default=None, description="PortName is the port name of prometheus JMX exporter port. If not specified, jmx-exporter will be used as the default.", alias="portName")
    __properties: ClassVar[List[str]] = ["configFile", "configuration", "jmxExporterJar", "port", "portName"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SparkV1beta2PrometheusSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SparkV1beta2PrometheusSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "configFile": obj.get("configFile"),
            "configuration": obj.get("configuration"),
            "jmxExporterJar": obj.get("jmxExporterJar") if obj.get("jmxExporterJar") is not None else '',
            "port": obj.get("port"),
            "portName": obj.get("portName")
        })
        return _obj


