# coding: utf-8

"""
    Kubeflow Spark Operator OpenAPI Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: unversioned
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from kubeflow_spark_api.models.io_k8s_api_core_v1_pod_template_spec import IoK8sApiCoreV1PodTemplateSpec
from typing import Optional, Set
from typing_extensions import Self

class SparkV1alpha1ExecutorSpec(BaseModel):
    """
    ExecutorSpec is specification of the executor.
    """ # noqa: E501
    core_limit: Optional[StrictStr] = Field(default=None, description="CoreLimit specifies the physical CPU limit for the pod, controlling the Kubernetes CPU limit. This is independent of `cores` (which controls the Spark task-slot count via `spark.driver.cores` or `spark.executor.cores`) and is validated as a Kubernetes resource quantity.  For a SparkConnect server, the operator creates the server pod directly as part of the client mode setup, so `coreLimit` is applied directly to the operator-created server pod's container `resources.limits.cpu`. For a SparkConnect executor, executor pods are created by Spark, so `coreLimit` is mapped to the Spark configuration key `spark.kubernetes.executor.limit.cores`, which Spark uses to set `resources.limits.cpu` on the executor pods.  Precedence (server only): if both this field and `spec.server.template.spec.containers[name=spark-kubernetes-driver].resources.limits.cpu` are set, this field wins for the CPU key. Other resource keys (memory, ephemeral-storage, etc.) on the template are preserved unchanged, matching the `addMemoryLimit` resource-merge convention used elsewhere in the project.  Valid values follow Kubernetes quantity format (e.g., \"500m\", \"1\", \"1.5\"). The value must be non-zero and, when `coreRequest` is also set, must be greater than or equal to `coreRequest`.", alias="coreLimit")
    core_request: Optional[StrictStr] = Field(default=None, description="CoreRequest specifies the physical CPU request for the pod, controlling the Kubernetes CPU request. This is independent of `cores` (which controls the Spark task-slot count via `spark.driver.cores` or `spark.executor.cores`) and is validated as a Kubernetes resource quantity.  For a SparkConnect server, the operator creates the server pod directly as part of the client mode setup, so `coreRequest` is applied directly to the operator-created server pod's container `resources.requests.cpu`. For a SparkConnect executor, executor pods are created by Spark, so `coreRequest` is mapped to the Spark configuration key `spark.kubernetes.executor.request.cores`, which Spark uses to set `resources.requests.cpu` on the executor pods.  Precedence (server only): if both this field and `spec.server.template.spec.containers[name=spark-kubernetes-driver].resources.requests.cpu` are set, this field wins for the CPU key. Other resource keys (memory, ephemeral-storage, etc.) on the template are preserved unchanged, matching the `addMemoryLimit` resource-merge convention used elsewhere in the project.  Valid values follow Kubernetes quantity format (e.g., \"500m\", \"1\", \"1.5\"). The value must be non-zero and, when `coreLimit` is also set, must not exceed `coreLimit`.", alias="coreRequest")
    cores: Optional[StrictInt] = Field(default=None, description="Cores maps to `spark.driver.cores` or `spark.executor.cores` for the driver and executors, respectively. Cores represents Spark task-slot/JVM concurrency and is independent of physical Kubernetes CPU requests and limits.")
    instances: Optional[StrictInt] = Field(default=None, description="Instances is the number of executor instances.")
    memory: Optional[StrictStr] = Field(default=None, description="Memory is the amount of memory to request for the pod.")
    template: Optional[IoK8sApiCoreV1PodTemplateSpec] = Field(default=None, description="Template is a pod template that can be used to define the driver or executor pod configurations that Spark configurations do not support. Spark version >= 3.0.0 is required. Ref: https://spark.apache.org/docs/latest/running-on-kubernetes.html#pod-template.")
    __properties: ClassVar[List[str]] = ["coreLimit", "coreRequest", "cores", "instances", "memory", "template"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SparkV1alpha1ExecutorSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of template
        if self.template:
            _dict['template'] = self.template.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SparkV1alpha1ExecutorSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "coreLimit": obj.get("coreLimit"),
            "coreRequest": obj.get("coreRequest"),
            "cores": obj.get("cores"),
            "instances": obj.get("instances"),
            "memory": obj.get("memory"),
            "template": IoK8sApiCoreV1PodTemplateSpec.from_dict(obj["template"]) if obj.get("template") is not None else None
        })
        return _obj


