# coding: utf-8

"""
    Kubeflow Spark Operator OpenAPI Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: unversioned
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class V1beta2DriverInfo(BaseModel):
    """
    DriverInfo captures information about the driver.
    """ # noqa: E501
    pod_name: Optional[StrictStr] = Field(default=None, alias="podName")
    web_ui_address: Optional[StrictStr] = Field(default=None, description="UI Details for the UI created via ClusterIP service accessible from within the cluster.", alias="webUIAddress")
    web_ui_ingress_address: Optional[StrictStr] = Field(default=None, alias="webUIIngressAddress")
    web_ui_ingress_name: Optional[StrictStr] = Field(default=None, description="Ingress Details if an ingress for the UI was created.", alias="webUIIngressName")
    web_ui_port: Optional[StrictInt] = Field(default=None, alias="webUIPort")
    web_ui_service_name: Optional[StrictStr] = Field(default=None, alias="webUIServiceName")
    __properties: ClassVar[List[str]] = ["podName", "webUIAddress", "webUIIngressAddress", "webUIIngressName", "webUIPort", "webUIServiceName"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1beta2DriverInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1beta2DriverInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "podName": obj.get("podName"),
            "webUIAddress": obj.get("webUIAddress"),
            "webUIIngressAddress": obj.get("webUIIngressAddress"),
            "webUIIngressName": obj.get("webUIIngressName"),
            "webUIPort": obj.get("webUIPort"),
            "webUIServiceName": obj.get("webUIServiceName")
        })
        return _obj


