// Code generated by k8s code-generator DO NOT EDIT.



// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// ScheduledSparkApplicationListerExpansion allows custom methods to be added to
// ScheduledSparkApplicationLister.
type ScheduledSparkApplicationListerExpansion interface{}

// ScheduledSparkApplicationNamespaceListerExpansion allows custom methods to be added to
// ScheduledSparkApplicationNamespaceLister.
type ScheduledSparkApplicationNamespaceListerExpansion interface{}

// SparkApplicationListerExpansion allows custom methods to be added to
// SparkApplicationLister.
type SparkApplicationListerExpansion interface{}

// SparkApplicationNamespaceListerExpansion allows custom methods to be added to
// SparkApplicationNamespaceLister.
type SparkApplicationNamespaceListerExpansion interface{}
