{
 "title": "Spark Applications",
 "tags": [ "SparkApplications" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster_name",
    "query": {
     "query": "label_values(kube_pod_owner{owner_kind=\"SparkApplication\"}, cluster_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_owner{owner_kind=\"SparkApplication\", cluster_name=~\"$cluster_name\"}, namespace)"
    }
   },
   {
    "name": "scheduled_sparkapp",
    "query": {
     "query": "label_values(kube_pod_owner{owner_kind=\"SparkApplication\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\"}, owner_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General stats by namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Spark Applications",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_owner{owner_kind=\"SparkApplication\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Finished Spark Applications",
   "type": "table",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n  kube_pod_owner{owner_kind=\"SparkApplication\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\"}\n  * on(pod)\n  kube_pod_start_time  * 1000\n)\n* on (pod) group_left(reason)\nkube_pod_container_status_terminated_reason{container!=\"pause\"}"
    }
   ]
  },
  {
   "title": "Running Spark Applications",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_owner{owner_kind=\"SparkApplication\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\"} \n  * on(pod) group_left(phase)\n  kube_pod_status_phase{phase=\"Running\"} == 1)\n\n",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Running Spark Applications",
   "type": "table",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "(\n  kube_pod_owner{owner_kind=\"SparkApplication\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\"}\n    * on(pod)\n  kube_pod_start_time * 1000\n)\n+ on(pod) group_left(phase)\n(kube_pod_status_phase{phase=\"Running\"} == 1)"
    }
   ]
  },
  {
   "title": "Failing Spark Applications",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_owner{owner_kind=\"SparkApplication\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\"} * on (pod) group_left(reason)\nkube_pod_container_status_terminated_reason{reason!=\"Completed\", container!=\"pause\"})\n\n",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Failing Spark Applications",
   "type": "table",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 11 },
   "targets": [
    {
     "expr": "(\n  kube_pod_owner{owner_kind=\"SparkApplication\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\"}\n    * on(pod)\n  kube_pod_start_time  * 1000\n)\n  * on (pod) group_left(reason)\nkube_pod_container_status_terminated_reason{reason!=\"Completed\", container!=\"pause\"}"
    }
   ]
  },
  { "title": "$scheduled_sparkapp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "scheduled_sparkapp" },
  {
   "title": "Spark Applications by status",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_owner{owner_kind=\"SparkApplication\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", owner_name=~\"$scheduled_sparkapp.*\"} * on(pod) group_left(phase) (kube_pod_status_phase == 1)) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Latest Run Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1,(\n  kube_pod_owner{owner_kind=\"SparkApplication\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", owner_name=~\"$scheduled_sparkapp.*\"}\n    * on(pod)\n  kube_pod_start_time\n)\n+ on(pod) group_left(phase)\n(kube_pod_status_phase == 1))",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Average Success Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n  (\n    (\n      kube_pod_owner{owner_kind=\"SparkApplication\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", owner_name=~\"$scheduled_sparkapp.*\"}\n      * on(pod) \n      kube_pod_container_status_terminated_reason{reason=\"Completed\"}\n    ) \n    * on(pod)\n    kube_pod_completion_time\n  \n  ) - (\n    (\n      kube_pod_owner{owner_kind=\"SparkApplication\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", owner_name=~\"$scheduled_sparkapp.*\"}\n      * on(pod) \n      kube_pod_container_status_terminated_reason{reason=\"Completed\"}\n    )\n    * on(pod)\n    kube_pod_start_time\n  )\n)"
    }
   ]
  },
  {
   "title": "Maximum Success Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  (\n    (\n      kube_pod_owner{owner_kind=\"SparkApplication\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", owner_name=~\"$scheduled_sparkapp.*\"}\n      * on(pod) \n      kube_pod_container_status_terminated_reason{reason=\"Completed\"}\n    ) \n    * on(pod)\n    kube_pod_completion_time\n  \n  ) - (\n    (\n      kube_pod_owner{owner_kind=\"SparkApplication\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", owner_name=~\"$scheduled_sparkapp.*\"}\n      * on(pod) \n      kube_pod_container_status_terminated_reason{reason=\"Completed\"}\n    )\n    * on(pod)\n    kube_pod_start_time\n  )\n)"
    }
   ]
  },
  {
   "title": "Minimum Success Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(\n  (\n    (\n      kube_pod_owner{owner_kind=\"SparkApplication\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", owner_name=~\"$scheduled_sparkapp.*\"}\n      * on(pod) \n      kube_pod_container_status_terminated_reason{reason=\"Completed\"}\n    ) \n    * on(pod)\n    kube_pod_completion_time\n  \n  ) - (\n    (\n      kube_pod_owner{owner_kind=\"SparkApplication\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", owner_name=~\"$scheduled_sparkapp.*\"}\n      * on(pod) \n      kube_pod_container_status_terminated_reason{reason=\"Completed\"}\n    )\n    * on(pod)\n    kube_pod_start_time\n  )\n)"
    }
   ]
  },
  {
   "title": "Spark Applications",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "(\n  kube_pod_owner{owner_kind=\"SparkApplication\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", owner_name=~\"$scheduled_sparkapp.*\"}\n    * on(pod)\n  kube_pod_start_time  * 1000\n)\n* on(pod) group_left(phase)\n(kube_pod_status_phase == 1)"
    }
   ]
  },
  {
   "title": "Status of failed pods",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "(\n  kube_pod_owner{owner_kind=\"SparkApplication\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", owner_name=~\"$scheduled_sparkapp.*\"}\n    * on(pod)\n  kube_pod_start_time  * 1000\n)\n* on (pod) group_left(reason)\nkube_pod_container_status_terminated_reason{reason!=\"Completed\", container!=\"pause\"}\n\n"
    }
   ]
  }
 ]
}