# permissions for end users to view scheduledsparkapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/managed-by: kustomize
  name: scheduledsparkapplication-viewer-role
rules:
- apiGroups:
  - sparkoperator.k8s.io
  resources:
  - scheduledsparkapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sparkoperator.k8s.io
  resources:
  - scheduledsparkapplications/status
  verbs:
  - get
