/*
Copyright 2025 The Kubeflow authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubeflow/spark-operator/v2/api/v1alpha1"
	apiv1alpha1 "github.com/kubeflow/spark-operator/v2/pkg/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSparkConnects implements SparkConnectInterface
type fakeSparkConnects struct {
	*gentype.FakeClientWithList[*v1alpha1.SparkConnect, *v1alpha1.SparkConnectList]
	Fake *FakeSparkoperatorV1alpha1
}

func newFakeSparkConnects(fake *FakeSparkoperatorV1alpha1, namespace string) apiv1alpha1.SparkConnectInterface {
	return &fakeSparkConnects{
		gentype.NewFakeClientWithList[*v1alpha1.SparkConnect, *v1alpha1.SparkConnectList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("sparkconnects"),
			v1alpha1.SchemeGroupVersion.WithKind("SparkConnect"),
			func() *v1alpha1.SparkConnect { return &v1alpha1.SparkConnect{} },
			func() *v1alpha1.SparkConnectList { return &v1alpha1.SparkConnectList{} },
			func(dst, src *v1alpha1.SparkConnectList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.SparkConnectList) []*v1alpha1.SparkConnect {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.SparkConnectList, items []*v1alpha1.SparkConnect) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
