/*
Copyright 2025 The Kubeflow authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/kubeflow/spark-operator/v2/api/v1alpha1"
	scheme "github.com/kubeflow/spark-operator/v2/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SparkConnectsGetter has a method to return a SparkConnectInterface.
// A group's client should implement this interface.
type SparkConnectsGetter interface {
	SparkConnects(namespace string) SparkConnectInterface
}

// SparkConnectInterface has methods to work with SparkConnect resources.
type SparkConnectInterface interface {
	Create(ctx context.Context, sparkConnect *apiv1alpha1.SparkConnect, opts v1.CreateOptions) (*apiv1alpha1.SparkConnect, error)
	Update(ctx context.Context, sparkConnect *apiv1alpha1.SparkConnect, opts v1.UpdateOptions) (*apiv1alpha1.SparkConnect, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, sparkConnect *apiv1alpha1.SparkConnect, opts v1.UpdateOptions) (*apiv1alpha1.SparkConnect, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.SparkConnect, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.SparkConnectList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.SparkConnect, err error)
	SparkConnectExpansion
}

// sparkConnects implements SparkConnectInterface
type sparkConnects struct {
	*gentype.ClientWithList[*apiv1alpha1.SparkConnect, *apiv1alpha1.SparkConnectList]
}

// newSparkConnects returns a SparkConnects
func newSparkConnects(c *SparkoperatorV1alpha1Client, namespace string) *sparkConnects {
	return &sparkConnects{
		gentype.NewClientWithList[*apiv1alpha1.SparkConnect, *apiv1alpha1.SparkConnectList](
			"sparkconnects",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.SparkConnect { return &apiv1alpha1.SparkConnect{} },
			func() *apiv1alpha1.SparkConnectList { return &apiv1alpha1.SparkConnectList{} },
		),
	}
}
