apiVersion: sparkoperator.k8s.io/v1beta1
kind: ScheduledSparkApplication
metadata:
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/managed-by: kustomize
  name: scheduledsparkapplication-sample
spec:
  # TODO(user): Add fields here
