// Code generated by k8s code-generator DO NOT EDIT.

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

type ScheduledSparkApplicationExpansion interface{}

type SparkApplicationExpansion interface{}
