// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/spark_submit.proto

package spark

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SparkSubmitService_RunAltSparkSubmit_FullMethodName = "/spark.SparkSubmitService/RunAltSparkSubmit"
)

// SparkSubmitServiceClient is the client API for SparkSubmitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Spark submit service definition.
type SparkSubmitServiceClient interface {
	RunAltSparkSubmit(ctx context.Context, in *RunAltSparkSubmitRequest, opts ...grpc.CallOption) (*RunAltSparkSubmitResponse, error)
}

type sparkSubmitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSparkSubmitServiceClient(cc grpc.ClientConnInterface) SparkSubmitServiceClient {
	return &sparkSubmitServiceClient{cc}
}

func (c *sparkSubmitServiceClient) RunAltSparkSubmit(ctx context.Context, in *RunAltSparkSubmitRequest, opts ...grpc.CallOption) (*RunAltSparkSubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunAltSparkSubmitResponse)
	err := c.cc.Invoke(ctx, SparkSubmitService_RunAltSparkSubmit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SparkSubmitServiceServer is the server API for SparkSubmitService service.
// All implementations must embed UnimplementedSparkSubmitServiceServer
// for forward compatibility.
//
// The Spark submit service definition.
type SparkSubmitServiceServer interface {
	RunAltSparkSubmit(context.Context, *RunAltSparkSubmitRequest) (*RunAltSparkSubmitResponse, error)
	mustEmbedUnimplementedSparkSubmitServiceServer()
}

// UnimplementedSparkSubmitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSparkSubmitServiceServer struct{}

func (UnimplementedSparkSubmitServiceServer) RunAltSparkSubmit(context.Context, *RunAltSparkSubmitRequest) (*RunAltSparkSubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunAltSparkSubmit not implemented")
}
func (UnimplementedSparkSubmitServiceServer) mustEmbedUnimplementedSparkSubmitServiceServer() {}
func (UnimplementedSparkSubmitServiceServer) testEmbeddedByValue()                            {}

// UnsafeSparkSubmitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SparkSubmitServiceServer will
// result in compilation errors.
type UnsafeSparkSubmitServiceServer interface {
	mustEmbedUnimplementedSparkSubmitServiceServer()
}

func RegisterSparkSubmitServiceServer(s grpc.ServiceRegistrar, srv SparkSubmitServiceServer) {
	// If the following call pancis, it indicates UnimplementedSparkSubmitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SparkSubmitService_ServiceDesc, srv)
}

func _SparkSubmitService_RunAltSparkSubmit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunAltSparkSubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSubmitServiceServer).RunAltSparkSubmit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSubmitService_RunAltSparkSubmit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSubmitServiceServer).RunAltSparkSubmit(ctx, req.(*RunAltSparkSubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SparkSubmitService_ServiceDesc is the grpc.ServiceDesc for SparkSubmitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SparkSubmitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spark.SparkSubmitService",
	HandlerType: (*SparkSubmitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunAltSparkSubmit",
			Handler:    _SparkSubmitService_RunAltSparkSubmit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/spark_submit.proto",
}
