// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.0
// source: sparksubmit/spark_submit.proto

package sparksubmit

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SparkSubmitService_Submit_FullMethodName = "/sparksubmit.SparkSubmitService/Submit"
)

// SparkSubmitServiceClient is the client API for SparkSubmitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SparkSubmitServiceClient interface {
	Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error)
}

type sparkSubmitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSparkSubmitServiceClient(cc grpc.ClientConnInterface) SparkSubmitServiceClient {
	return &sparkSubmitServiceClient{cc}
}

func (c *sparkSubmitServiceClient) Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error) {
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, SparkSubmitService_Submit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SparkSubmitServiceServer is the server API for SparkSubmitService service.
// All implementations must embed UnimplementedSparkSubmitServiceServer
// for forward compatibility
type SparkSubmitServiceServer interface {
	Submit(context.Context, *SubmitRequest) (*SubmitResponse, error)
	mustEmbedUnimplementedSparkSubmitServiceServer()
}

// UnimplementedSparkSubmitServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSparkSubmitServiceServer struct {
}

func (UnimplementedSparkSubmitServiceServer) Submit(context.Context, *SubmitRequest) (*SubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedSparkSubmitServiceServer) mustEmbedUnimplementedSparkSubmitServiceServer() {}

// UnsafeSparkSubmitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SparkSubmitServiceServer will
// result in compilation errors.
type UnsafeSparkSubmitServiceServer interface {
	mustEmbedUnimplementedSparkSubmitServiceServer()
}

func RegisterSparkSubmitServiceServer(s grpc.ServiceRegistrar, srv SparkSubmitServiceServer) {
	s.RegisterService(&SparkSubmitService_ServiceDesc, srv)
}

func _SparkSubmitService_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSubmitServiceServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSubmitService_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSubmitServiceServer).Submit(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SparkSubmitService_ServiceDesc is the grpc.ServiceDesc for SparkSubmitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SparkSubmitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sparksubmit.SparkSubmitService",
	HandlerType: (*SparkSubmitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _SparkSubmitService_Submit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sparksubmit/spark_submit.proto",
}
