// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.0
// source: sparksubmit/spark_submit.proto

package sparksubmit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request used by SparkSubmitService.Submit
type SubmitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name to use for the SparkApplication (optional depending on server)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The SparkApplication content serialized as JSON (tests refer to ApplicationJson).
	ApplicationJson string `protobuf:"bytes,2,opt,name=application_json,json=applicationJson,proto3" json:"application_json,omitempty"`
	// optional namespace
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sparksubmit_spark_submit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sparksubmit_spark_submit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_sparksubmit_spark_submit_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubmitRequest) GetApplicationJson() string {
	if x != nil {
		return x.ApplicationJson
	}
	return ""
}

func (x *SubmitRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// Response returned by SparkSubmitService.Submit
type SubmitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// whether submission succeeded
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// human readable message or error
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// created application name (optional)
	ApplicationName string `protobuf:"bytes,3,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sparksubmit_spark_submit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sparksubmit_spark_submit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_sparksubmit_spark_submit_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SubmitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitResponse) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

var File_sparksubmit_spark_submit_proto protoreflect.FileDescriptor

var file_sparksubmit_spark_submit_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x70, 0x61, 0x72, 0x6b, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x2f, 0x73, 0x70,
	0x61, 0x72, 0x6b, 0x5f, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x73, 0x70, 0x61, 0x72, 0x6b, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x22, 0x6c, 0x0a,
	0x0d, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x1c, 0x0a,
	0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x65, 0x0a, 0x0e, 0x53,
	0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x32, 0x57, 0x0a, 0x12, 0x53, 0x70, 0x61, 0x72, 0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x06, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x12, 0x1a, 0x2e, 0x73, 0x70, 0x61, 0x72, 0x6b, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x73, 0x70, 0x61, 0x72, 0x6b, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x2e, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x46, 0x5a, 0x44, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x66, 0x6c,
	0x6f, 0x77, 0x2f, 0x73, 0x70, 0x61, 0x72, 0x6b, 0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x2f, 0x76, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x61, 0x72, 0x6b,
	0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x3b, 0x20, 0x73, 0x70, 0x61, 0x72, 0x6b, 0x73, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sparksubmit_spark_submit_proto_rawDescOnce sync.Once
	file_sparksubmit_spark_submit_proto_rawDescData = file_sparksubmit_spark_submit_proto_rawDesc
)

func file_sparksubmit_spark_submit_proto_rawDescGZIP() []byte {
	file_sparksubmit_spark_submit_proto_rawDescOnce.Do(func() {
		file_sparksubmit_spark_submit_proto_rawDescData = protoimpl.X.CompressGZIP(file_sparksubmit_spark_submit_proto_rawDescData)
	})
	return file_sparksubmit_spark_submit_proto_rawDescData
}

var file_sparksubmit_spark_submit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sparksubmit_spark_submit_proto_goTypes = []interface{}{
	(*SubmitRequest)(nil),  // 0: sparksubmit.SubmitRequest
	(*SubmitResponse)(nil), // 1: sparksubmit.SubmitResponse
}
var file_sparksubmit_spark_submit_proto_depIdxs = []int32{
	0, // 0: sparksubmit.SparkSubmitService.Submit:input_type -> sparksubmit.SubmitRequest
	1, // 1: sparksubmit.SparkSubmitService.Submit:output_type -> sparksubmit.SubmitResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sparksubmit_spark_submit_proto_init() }
func file_sparksubmit_spark_submit_proto_init() {
	if File_sparksubmit_spark_submit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sparksubmit_spark_submit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sparksubmit_spark_submit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sparksubmit_spark_submit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sparksubmit_spark_submit_proto_goTypes,
		DependencyIndexes: file_sparksubmit_spark_submit_proto_depIdxs,
		MessageInfos:      file_sparksubmit_spark_submit_proto_msgTypes,
	}.Build()
	File_sparksubmit_spark_submit_proto = out.File
	file_sparksubmit_spark_submit_proto_rawDesc = nil
	file_sparksubmit_spark_submit_proto_goTypes = nil
	file_sparksubmit_spark_submit_proto_depIdxs = nil
}
