name: Release Charts

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    environment: 'prod'
    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: Azure/login@v2
        with:
          client-id: ${{ secrets.DDO_SPARK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Get secrets
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ secrets.KEY_VAULT }}
          secrets: "acrUsername, acrPassword"
        id: kv

      - name: Login to docker
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ steps.kv.outputs.acrUsername }}
          password: ${{ steps.kv.outputs.acrPassword }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.IMAGE }}
          flavor: |
            latest=false
            prefix=v1beta2-1.3.8-3.1.1-

      - name: Get spark version
        id: get-spark-version
        run: |
          # Read the file and trim whitespace/newlines
          SPARK_VERSION=$(cat spark-version | xargs)
          # Ensure version starts with 'v'
          if [[ "$SPARK_VERSION" == v* ]]; then
            SPARK_VERSION="$SPARK_VERSION"
          else
            SPARK_VERSION="v$SPARK_VERSION"
          fi
          SPARK_IMAGE=${{vars.SPARK_IMAGE_PATH}}:${SPARK_VERSION}
          echo "Read spark version: ${SPARK_IMAGE}"
          echo "SPARK_IMAGE=${SPARK_IMAGE}" >> "$GITHUB_OUTPUT"
          
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SPARK_IMAGE=${{ steps.get-spark-version.outputs.SPARK_IMAGE }}
