name: Release Latest Images

on:
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  images:
    name: Build and push latest images
    if: github.repository == 'kubeflow/spark-operator'

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-and-push-images.yaml
    with:
      ref: ${{ github.sha }}
      version: latest
      publish: true
